services:
  polly:
    build: .
    user: "1000:1000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./data:/app/data
      - ./static/uploads:/app/static/uploads
      - ./logs:/app/logs
      - ./db:/app/db
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - polly-network
  redis:
    image: redis:7-alpine
    container_name: polly-redis
    ports:
      - "6340:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-polly_redis_pass}
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD:-polly_redis_pass}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - polly-network
volumes:
  polly_db:
  redis_data:

networks:
  polly-network:
    driver: bridge